package trabalhoCG;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.PopupMenu;
import javax.swing.*;

import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
/**
 *
 * @author Marcos Vinicius
 */

public class Janela extends javax.swing.JFrame {
        
    /** Creates new form Janela */
    public Janela() {
        
        initComponents();
        
          this.setTitle("Algoritmo e Geração de Linhas - todos os algoritmos");
           // this.setSize(600,600);
            this.setDefaultCloseOperation(EXIT_ON_CLOSE);
            this.setLocationRelativeTo(null);
            this.setVisible(true);
             add(new TodasLinhas( 10, 40,10,90));
           
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDesenho = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelPosx = new javax.swing.JLabel();
        labelPosY = new javax.swing.JLabel();
        positionX = new javax.swing.JLabel();
        positionY = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDesenho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelDesenhoMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelDesenhoMouseMoved(evt);
            }
        });
        panelDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDesenhoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelDesenhoLayout = new javax.swing.GroupLayout(panelDesenho);
        panelDesenho.setLayout(panelDesenhoLayout);
        panelDesenhoLayout.setHorizontalGroup(
            panelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelDesenhoLayout.setVerticalGroup(
            panelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(240, 240, 230));

        labelPosx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPosx.setBorder(javax.swing.BorderFactory.createTitledBorder("X"));

        labelPosY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPosY.setBorder(javax.swing.BorderFactory.createTitledBorder("Y"));

        positionX.setBorder(javax.swing.BorderFactory.createTitledBorder("X"));

        positionY.setBorder(javax.swing.BorderFactory.createTitledBorder("Y"));

        jLabel1.setText("Posições escolhidas:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelPosx, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPosY, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(positionX, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(positionY, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(positionY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(positionX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPosx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPosY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32))
        );

        jMenu1.setText("Primitivas");
        jMenu1.setMinimumSize(new java.awt.Dimension(75, 30));
        jMenu1.setPreferredSize(new java.awt.Dimension(80, 39));

        jMenu3.setText("Linhaas");

        jMenuItem1.setText("Analítico");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("DDA");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Bresenham");
        jMenu3.add(jMenuItem3);

        jMenu1.add(jMenu3);

        jMenu4.setText("Poligonos");

        jMenuItem4.setText("Varredura");
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("BoundarFill");
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Análise Geométrica");
        jMenu4.add(jMenuItem6);

        jMenu1.add(jMenu4);

        jMenu5.setText("Circulos");

        jMenuItem7.setText("Paramétrica");
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("Incremental com Simetria");
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Bresenham");
        jMenu5.add(jMenuItem9);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cores");

        jMenuItem10.setText("Azul");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Vermelho");
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Azul");
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Amarelo");
        jMenu2.add(jMenuItem13);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDesenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
              
    }//GEN-LAST:event_jMenuItem1ActionPerformed
 
    private void panelDesenhoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDesenhoMouseMoved
            mousePos = panelDesenho.getMousePosition();
            labelPosx.setText(String.valueOf(mousePos.x));
            labelPosY.setText(String.valueOf(mousePos.y));
    }//GEN-LAST:event_panelDesenhoMouseMoved

    private void panelDesenhoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDesenhoMouseDragged
        mousePos = panelDesenho.getMousePosition();
            labelPosx.setText(String.valueOf(mousePos.x));
            labelPosY.setText(String.valueOf(mousePos.y));
    }//GEN-LAST:event_panelDesenhoMouseDragged
   
    private void panelDesenhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDesenhoMouseClicked
        int x = 0,y = 0,x2=0,y2=0; 
        mousePos = panelDesenho.getMousePosition();
         
            if(cont==0){
            x=mousePos.x;
            y=mousePos.y;
            positionX.setText(String.valueOf(mousePos.x ));
            positionY.setText(String.valueOf(mousePos.y));
            cont++;
            }else{
                positionX.setText(String.valueOf(mousePos.x));
                positionY.setText(String.valueOf(mousePos.y));
                x2=mousePos.x;
                y2=mousePos.y;
                
                add(new TodasLinhas( x, y,x2,y2));
                cont--;
            }
            
    }//GEN-LAST:event_panelDesenhoMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });

   
    }
    protected int cont=0;
    protected Point mousePos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelPosY;
    private javax.swing.JLabel labelPosx;
    private javax.swing.JPanel panelDesenho;
    private javax.swing.JLabel positionX;
    private javax.swing.JLabel positionY;
    // End of variables declaration//GEN-END:variables

}
